export const categoriasData = [
    {
        "cod_cat": "4",
        "nom_cat": "Noticia",
        "nom_cur_cat": "Noticia",
        "relacion_cat": "1",
        "orden_cat": "2",
        "imp_cat": "0",
        "entregas_cat": "3,1,1,3",
        "desc_cat": "Es el relato de un hecho novedoso o desconocido que interesa a las audiencias por su inmediatez, impacto y relevancia.</br></br><em>En esta categor&#237;a se valoran la rapidez y la precisi&#243;n con la que se divulg&#243; la noticia, su contextualizaci&#243;n y la calidad de las fuentes. Se tiene en cuenta que haya sido primicia y si tuvo seguimiento con un desarrollo ampliado en varias emisiones o entregas.</em>",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label>\r\n\r\n\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "3",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "3",
        "nom_cat": "Periodismo investigativo",
        "nom_cur_cat": "Periodismo Investigativo",
        "relacion_cat": "1",
        "orden_cat": "4",
        "imp_cat": "0",
        "entregas_cat": "3,1,1,3",
        "desc_cat": "El periodista, por medio de la b&#250;squeda y el an&#225;lisis de la informaci&#243;n proveniente de diversidad de fuentes confiables, aporta datos y evidencias que se desconoc&#237;an y llega a nuevas conclusiones sobre los hechos.\r\n<\/br><\/br>\r\n<em>En esta categor&iacute;a se valora que el trabajo revele hechos que permanec&iacute;an ocultos o ignorados a partir de aportar las pruebas necesarias, demuestre un manejo riguroso y &eacute;tico de la informaci&oacute;n, tenga carga de denuncia e interpele alg&uacute;n poder que se haya extralimitado.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label>\r\n\r\n\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "3",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "1",
        "entrega3": "1"
    },

   
    {
        "cod_cat": "1",
        "nom_cat": "Cr&#211;nica",
        "nom_cur_cat": "Cr&#243;nica",
        "relacion_cat": "1",
        "orden_cat": "10",
        "imp_cat": "0",
        "entregas_cat": "3,1,1,3",
        "desc_cat": "Es el relato de un hecho noticioso o de inter&eacute;s humano desde el punto de vista del autor, que se caracteriza por la variedad de t&eacute;cnicas narrativas, como el uso de la primera persona y la polifon&iacute;a de voces, el manejo del tiempo y la recreaci&oacute;n de los hechos.\r\n<\/br><\/br>\r\n<em>En esta categor&iacute;a se valoran la mirada y la voz particular del cronista, apoyadas en un trabajo riguroso de investigaci&oacute;n.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label >\r\n\r\n\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "3",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "1",
        "entrega3": "1"
    },

    


    {
        "cod_cat": "14",
        "nom_cat": "Reportaje",
        "nom_cur_cat": "Reportaje",
        "relacion_cat": "1",
        "orden_cat": "20",
        "imp_cat": "0",
        "entregas_cat": "3,1,1,3",
        "desc_cat": "Es la historia completa de un hecho de actualidad, presentada con pluralidad de  fuentes, contexto y estrategia narrativa.\r\n<\/br><\/br>\r\n<em>En esta categor&#237;a se valoran la reconstrucci&#243;n minuciosa de los hechos, la capacidad interpretativa del autor, la calidad de las fuentes, la verificaci&#243;n de la informaci&#243;n y la variedad de recursos narrativos, seg&#250;n el medio de producci&#243;n.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label>\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "3",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "9",
        "nom_cat": "Opini&#243;n y an&#225;lisis",
        "nom_cur_cat": "Opini&#243;n y an&#225;lisis",
        "relacion_cat": "1",
        "orden_cat": "40",
        "imp_cat": "0",
        "entregas_cat": "1,1,1,1",
        "desc_cat": "Con la exposici&oacute;n de argumentos sustentados, los espacios de opini&oacute;n y de an&aacute;lisis promueven la discusi&oacute;n de temas de inter&eacute;s p&uacute;blico y humano, contribuyendo a la formaci&oacute;n de audiencias m&aacute;s cr&iacute;ticas y participativas. Se admiten columnas y art&iacute;culos de opini&oacute;n, as&iacute; como formatos de an&aacute;lisis y debate.\r\n",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label >",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "1",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "1",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "23",
        "nom_cat": "Humor",
        "nom_cur_cat": "Humor",
        "relacion_cat": "1",
        "orden_cat": "45",
        "imp_cat": "0",
        "entregas_cat": "1,1,1,1",
        "desc_cat": "El humor es una forma inteligente de hacer cr&iacute;tica con cargas de profundidad insospechadas. Por ello nunca pierde su vigencia el cl&aacute;sico g&eacute;nero de la s&aacute;tira pol&iacute;tica y social, en registros que van desde la iron&iacute;a sutil hasta el sarcasmo. El humor aporta contexto e invita a la reflexi&oacute;n con ingenio, lenguaje popular y tono provocador, sumados a variedad de recursos ret&oacute;ricos y audiovisuales.",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) puede presentarse m&#225;ximo una (1) entrega sobre el mismo hecho.<\/label>\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "1",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "1",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "8",
        "nom_cat": "Cr&#205;tica",
        "nom_cur_cat": "Cr&#237;tica",
        "relacion_cat": "1",
        "orden_cat": "50",
        "imp_cat": "0",
        "entregas_cat": "1,1,1,1",
        "desc_cat": "Es el comentario o rese&#241;a sobre un objeto art&#237;stico o una expresi&#243;n cultural que aporta juicios de valor sujetos a los c&#225;nones est&#233;ticos y a la tradici&#243;n del g&#233;nero. Cumple las funciones de informar, interpretar y valorar para tender un puente entre la obra de creaci&#243;n y el p&#250;blico.\r\n<\/br><\/br>\r\nSe considerar&#225;n las cr&#237;ticas literarias, art&#237;sticas, musicales, teatrales, de danza, cinematogr&#225;ficas, gastron&#243;micas, arquitect&#243;nicas, urban&#237;sticas y de viaje, as&#237; como la cr&#237;tica de medios de comunicaci&#243;n tradicionales y digitales.\r\n<\/br><\/br>\r\n<em>En esta categor&iacute;a se valoran la independencia de criterio, la creatividad y la argumentaci&oacute;n, as&iacute; como el aporte a la formaci&oacute;n de p&uacute;blicos m&aacute;s sensibles y conocedores.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) puede presentarse m&#225;ximo una (1) entrega sobre el mismo hecho.<\/label>\r\n\r\n\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">En audio y en video pueden presentarse m&aacute;ximo tres (3) emisiones sobre el mismo hecho, cuya duraci&oacute;n m&aacute;xima total sea de una (1) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "1",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "1",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "6",
        "nom_cat": "Caricatura",
        "nom_cur_cat": "Caricatura",
        "relacion_cat": "0",
        "orden_cat": "60",
        "imp_cat": "0",
        "entregas_cat": "3,0,0,3",
        "desc_cat": "Con la intenci&oacute;n de hacer una cr&iacute;tica gr&aacute;fica, los caricaturistas describen los hechos y personajes de manera irreverente a trav&eacute;s de un g&eacute;nero que relaciona el humor, el arte, la historia y el periodismo.\r\n<\/br><\/br>\r\n<em>En esta categor&iacute;a se valoran la originalidad, la calidad del dibujo, y la carga simb&oacute;lica y cr&iacute;tica de la caricatura.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\">En esta categor&#237;a pueden presentarse entre una (1) y tres (3) caricaturas.<\/label>",
        "esp1_cat": "",
        "num1_cat": "3",
        "num2_cat": "3",
        "num3_cat": "0",
        "num4_cat": "0",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "0",
        "entrega3": "0"
    },
    // {
    //     "cod_cat": "21",
    //     "nom_cat": "FOTOPERIODISMO",
    //     "nom_cur_cat": "Fotoperiodismo",
    //     "relacion_cat": "0",
    //     "orden_cat": "65",
    //     "imp_cat": "0",
    //     "entregas_cat": "0",
    //     "desc_cat": "En esta categor&iacute;a se entregar&aacute;n dos premios:<br><br>-&nbsp;&nbsp;<strong>Fotograf&iacute;a period&iacute;stica<\/strong><br \/>-&nbsp;&nbsp;<strong>Reportaje gr&aacute;fico<\/strong>\r\n<br>\r\n<div class=\"det_fot\">\r\n<em >En Fotoperiodismo se valora el registro visual de un hecho por su riqueza informativa, encuadre original y fuerza est&eacute;tica. Se tendr&aacute;n en cuenta im&aacute;genes que no hayan sido manipuladas o alteradas m&aacute;s all&aacute; de lo necesario para publicarse en un medio<\/em><div>",
    //     "esp_cat": "",
    //     "esp1_cat": "",
    //     "num1_cat": "0",
    //     "num2_cat": "0",
    //     "num3_cat": "0",
    //     "num4_cat": "0",
    //     "fec_crea": null,
    //     "fec_modif": null,
    //     "usu_acce": null,
    //     "reg_eli": "0",
    //     "entrega1": "0",
    //     "entrega2": null,
    //     "entrega3": null
    // },
    {
        "cod_cat": "5",
        "nom_cat": "Fotograf&iacute;a period&iacute;stica",
        "nom_cur_cat": "Fotograf&iacute;a period&iacute;stica",
        "relacion_cat": "0",
        "orden_cat": "70",
        "imp_cat": "0",
        "entregas_cat": "3,0,0,3",
        "desc_cat": "Es una imagen que por su car&aacute;cter informativo, instantaneidad, impacto y relevancia logra capturar la esencia de un hecho noticioso.\r\n",
        "esp_cat": "<label class=\"gLabel featured\">En esta categor&#237;a puede presentarse una (1) fotograf&#237;a.<\/label>",
        "esp1_cat": "",
        "num1_cat": "1",
        "num2_cat": "1",
        "num3_cat": "0",
        "num4_cat": "0",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "0",
        "entrega3": "0"
    },
    {
        "cod_cat": "18",
        "nom_cat": "Reportaje gr&aacute;fico",
        "nom_cur_cat": "Reportaje gr&aacute;fico",
        "relacion_cat": "0",
        "orden_cat": "70",
        "imp_cat": "0",
        "entregas_cat": "3,0,0,3",
        "desc_cat": "Es una secuencia de im&aacute;genes que narran un hecho de actualidad o de inter&eacute;s humano a trav&eacute;s de una serie o galer&iacute;a de fotos en torno a un mismo tema o acontecimiento. La informaci&oacute;n esencial debe estar contenida en las fotograf&iacute;as y no supeditada a los textos de apoyo.",
        "esp_cat": "<label class=\"gLabel featured\">Pueden presentarse entre tres (3) y catorce (14) fotograf&iacute;as.<\/label>",
        "esp1_cat": "",
        "num1_cat": "1",
        "num2_cat": "1",
        "num3_cat": "0",
        "num4_cat": "0",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "3",
        "entrega2": "0",
        "entrega3": "0"
    },
  
    {
        "cod_cat": "15",
        "nom_cat": "Multimedia",
        "nom_cur_cat": "Multimedia",
        "relacion_cat": "1",
        "orden_cat": "73",
        "imp_cat": "0",
        "entregas_cat": "1,1,1,1",
        "desc_cat": "Un trabajo multimedia combina diferentes lenguajes y formatos explorando las tendencias convergentes, interactivas y tecnol&oacute;gicas aplicadas a los nuevos medios en la web y en las redes sociales. <br><br>A diferencia de las categor&iacute;as anteriores, en esta es un requisito que confluyan la mayor cantidad de recursos multimediales.\r\n<br><br><em>\r\nEn esta categor&iacute;a se valoran la calidad y la unidad comunicativa de la pieza period&iacute;stica; la capacidad de armonizar los diferentes lenguajes textuales, audiovisuales y gr&aacute;ficos; la utilizaci&oacute;n de herramientas innovadoras y el uso correcto de las plataformas multimediales.<\/em>",
        "esp_cat": "<label class=\"gLabel featured\"> En esta categor&iacute;a debe presentarse la direcci&oacute;n&nbsp;URL de la pieza period&iacute;stica en la que se encuentre&nbsp;todo el contenido del trabajo que concursa.<\/label>\r\n",
        "esp1_cat": "",
        "num1_cat": "1",
        "num2_cat": "1",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "1",
        "entrega2": "1",
        "entrega3": "1"
    },
    {
        "cod_cat": "7",
        "nom_cat": "Est&iacute;mulos al Periodismo Universitario",
        "nom_cur_cat": "Est&iacute;mulos al Periodismo Universitario",
        "relacion_cat": "1",
        "orden_cat": "75",
        "imp_cat": "0",
        "entregas_cat": "1,1,1,1",
        "desc_cat": "El Premio Nacional de Periodismo Sim&oacute;n Bol&iacute;var ratifica su voto de confianza en la academia responsable de la formaci&oacute;n de las nuevas generaciones de periodistas. Con los Est&iacute;mulos al Periodismo Universitario se busca alentar el ejercicio riguroso y creativo de quienes se inician en el oficio con el acompa&ntilde;amiento imprescindible de sus profesores.\r\n\r\n<p>Los requisitos para participar son:<\/p>\r\n\r\n<ul>\r\n<li>Pueden presentarse trabajos individuales o colectivos.<\/li>\r\n<li>Los participantes deben tener m&aacute;ximo 26 a&ntilde;os de&nbsp;edad al cierre de la convocatoria y ser estudiantes de&nbsp;una Instituci&oacute;n de Educaci&oacute;n Superior.<\/li>\r\n<li>El participante debe tener nacionalidad colombiana o demostrar residencia permanente en el pa&iacute;s a trav&eacute;s de la c&eacute;dula de extranjer&iacute;a.<\/li>\r\n<li>Para la inscripci&oacute;n de cada trabajo la Instituci&oacute;n de&nbsp;Educaci&oacute;n Superior (IES) debe certificar que el medio&nbsp;en el que se public&oacute; o emiti&oacute; el trabajo est&aacute; vinculado&nbsp;a la IES y que los participantes inscritos son&nbsp;estudiantes de alguno de sus programas acad&eacute;micos.&nbsp;&nbsp;Descargue el modelo de certificado <span style=\"text-decoration: underline;\"><strong><a href=\"https:\/\/psb.premiosimonbolivar.com\/docs\/Formato_Certificado_Pub_Estimulos2023.docx\" target=\"_blank\" rel=\"noopener\">aqu&iacute;<\/a><\/strong><\/span>.<\/li>\r\n<li>Los participantes de los Est&iacute;mulos al Periodismo Universitario no podr&aacute;n inscribir trabajos en ninguna otra categor&iacute;a.<\/li>\r\n<li>El premio se entrega al participante, no al medio universitario.<\/li>\r\n<\/ul",
        "esp_cat": "<label class=\"gLabel featured\">En texto (impreso y digital) pueden presentarse m&#225;ximo tres (3) entregas sobre el mismo hecho.<\/label>\r\n\r\n\r\n\r\n",
        "esp1_cat": "<label class=\"gLabel featured\">\r\nEn audio y video pueden presentarse m&#225;ximo tres (3) entregas o varias emisiones sobre el mismo hecho, cuya duraci&#243;n m&#225;xima total sea de una (3) hora.<\/label>",
        "num1_cat": "3",
        "num2_cat": "1",
        "num3_cat": "1",
        "num4_cat": "1",
        "fec_crea": null,
        "fec_modif": null,
        "usu_acce": null,
        "reg_eli": "0",
        "entrega1": "1",
        "entrega2": "1",
        "entrega3": "1"
    },

]